// resources/js/views/Login.vue
<template>
  <div>
      <a href="/">
          <img
              class="block mx-auto h-auto w-48"
              src="/logo.png"
              alt="logo"
          />
      </a>
    <h2 class="mt-4 text-center text-3xl font-extrabold text-gray-900">
      {{ $t('enter_account')}}
    </h2>
    <p class="mt-2 text-center text-md text-gray-600">
        {{ $t('not_account')}}
      <router-link
        :to="{ name: 'Register' }"
        class="font-medium text-indigo-600 hover:text-indigo-500"
      >
          {{ $t('make_register')}}
      </router-link>
    </p>
  </div>
  <form class="mt-8 space-y-6" @submit="login">
    <Alert v-if="errorMsg">
      {{ errorMsg }}
      <span
        @click="errorMsg = ''"
        class="w-8 h-8 flex items-center justify-center rounded-full transition-colors cursor-pointer hover:bg-[rgba(0,0,0,0.2)]"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-6 w-6"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M6 18L18 6M6 6l12 12"
          />
        </svg>
      </span>
    </Alert>
    <input type="hidden" name="remember" value="true" />
    <div class="rounded-md shadow-sm -space-y-px">
      <div>
        <label for="email-address" class="sr-only">Email address</label>
        <input
          id="email-address"
          name="email"
          type="email"
          autocomplete="email"
          required=""
          v-model="user.email"
          class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
          placeholder="Email address"
        />
      </div>
      <div>
        <label for="password" class="sr-only">{{ $t('password')}}</label>
        <input
          id="password"
          name="password"
          type="password"
          autocomplete="current-password"
          required=""
          v-model="user.password"
          class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
          placeholder="Құпия сөз"
        />
      </div>
    </div>

    <div class="flex items-center justify-between">
      <div class="flex items-center">
        <input
          id="remember-me"
          name="remember-me"
          type="checkbox"
          v-model="user.remember"
          class="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded"
        />
        <label for="remember-me" class="ml-2 block text-sm text-gray-900">
            {{ $t('remember')}}
        </label>
      </div>

        <div>
            <router-link :to="{name: 'ForgotPassword'}" class="text-sm text-gray-600">{{ $t('forgot_password')}}</router-link>
        </div>
    </div>

    <div>
      <button
        type="submit"
        :disabled="loading"
        class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
        :class="{
          'cursor-not-allowed': loading,
          'hover:bg-indigo-500': loading,
        }"
      >
        <span class="absolute left-0 inset-y-0 flex items-center pl-3">
          <LockClosedIcon
            class="h-5 w-5 text-indigo-500 group-hover:text-indigo-400"
            aria-hidden="true"
          />
        </span>
        <svg
          v-if="loading"
          class="animate-spin -ml-1 mr-3 h-5 w-5 text-white"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
        >
          <circle
            class="opacity-25"
            cx="12"
            cy="12"
            r="10"
            stroke="currentColor"
            stroke-width="4"
          ></circle>
          <path
            class="opacity-75"
            fill="currentColor"
            d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
          ></path>
        </svg>
          {{ $t('login')}}
      </button>
        <div class="mt-2">
            <GoogleLogin :callback="callback"
                         clientId="292704683290-uqm9jjau6r4vcbi5kn7upc7go9k8mebf.apps.googleusercontent.com"
                         :button-config="{
            locale: 'kk-KK'
            }"/>
        </div>
    </div>
  </form>
</template>

<script setup>
import {defineAsyncComponent} from "vue";
import { LockClosedIcon } from "@heroicons/vue/24/outline";
import store from "../store";
import { useRouter } from "vue-router";
import { ref } from "vue";
//import Alert from "../components/Alert.vue";
import { decodeCredential } from 'vue3-google-login'
import {GoogleLogin} from 'vue3-google-login'

const Alert = defineAsyncComponent(() =>
    import('../components/Alert.vue')
);
/*const GoogleLogin = defineAsyncComponent(() =>
    import('vue3-google-login')
);*/

const router = useRouter();

const user = {
  email: "",
  password: "",
};
let loading = ref(false);
let errorMsg = ref("");

function login(ev) {
  ev.preventDefault();

  loading.value = true;
  store
    .dispatch("login", user)
    .then(() => {
      loading.value = false;
      router.push({name:"Step1"});
    })
    .catch((err) => {
      console.log(err.response)
      loading.value = false;
      errorMsg.value = err.response.data.message;
    });
}
function callback(res){
    if (res.credential){
        loading.value = true;
        store
            .dispatch("googleLogin", decodeCredential(res.credential))
            .then(() => {
                loading.value = false;
                router.push({name:"Step1"});
            })
            .catch((err) => {
                console.log(err)
                loading.value = false;
                errorMsg.value = err.response.data.message;
            });
    }
}
</script>

// frontend/src/app/[locale]/(auth)/login/page.tsx
'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { LockClosedIcon } from '@heroicons/react/24/solid';
import { useUserStore } from '@/store/useUserStore';
import Alert from '@/components/Alert';
import apiClient from '@/lib/api-client';
import { GoogleLogin } from '@react-oauth/google';
import { jwtDecode } from 'jwt-decode';

export default function LoginPage() {
    const router = useRouter();
    const { setToken, setUser, token, _hasHydrated } = useUserStore();

    React.useEffect(() => {
        if (_hasHydrated && token) {
            router.push('/');
        }
    }, [_hasHydrated, token, router]);

    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [remember, setRemember] = useState(false);
    const [loading, setLoading] = useState(false);
    const [errorMsg, setErrorMsg] = useState('');

    const login = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);
        setErrorMsg('');

        try {
            const { data } = await apiClient.post('/login', {
                email,
                password,
                remember
            });

            setToken(data.token);
            setUser(data.user);

            router.push('/');
        } catch (err: any) {
            console.error(err);
            setErrorMsg(err.response?.data?.message || 'Қате орын алды');
        } finally {
            setLoading(false);
        }
    };

    const handleGoogleSuccess = async (credentialResponse: any) => {
        if (credentialResponse.credential) {
            setLoading(true);
            setErrorMsg('');
            try {
                const decoded: any = jwtDecode(credentialResponse.credential);
                const { data } = await apiClient.post('/login-google', {
                    sub: decoded.sub,
                    email: decoded.email,
                    name: decoded.name,
                });

                setToken(data.token);
                setUser(data.user);

                router.push('/');
            } catch (err: any) {
                console.error(err);
                setErrorMsg(err.response?.data?.message || 'Google арқылы кіру кезінде қате орын алды');
            } finally {
                setLoading(false);
            }
        }
    };

    return (
        <>
            <h2 className="mt-4 text-center text-3xl font-semibold font-roboto text-gray-900">
                Аккаунтыңызға кіріңіз
            </h2>
            <p className="mt-2 text-center text-md text-gray-600">
                Аккаунтыңыз жоқ па?{' '}
                <Link href="/register" className="font-medium text-indigo-600 hover:text-indigo-500">
                    Тіркелу
                </Link>
            </p>

            <form className="mt-8 space-y-6" onSubmit={login}>
                {errorMsg && (
                    <Alert className="relative">
                        {errorMsg}
                        <span
                            onClick={() => setErrorMsg('')}
                            className="absolute right-2 top-2 p-1 cursor-pointer"
                        >
                            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                <path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clipRule="evenodd" />
                            </svg>
                        </span>
                    </Alert>
                )}

                <div className="rounded-md shadow-sm -space-y-px">
                    <div>
                        <input
                            type="email"
                            required
                            className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                            placeholder="Email address"
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                        />
                    </div>
                    <div>
                        <input
                            type="password"
                            required
                            className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                            placeholder="Құпия сөз"
                            value={password}
                            onChange={(e) => setPassword(e.target.value)}
                        />
                    </div>
                </div>

                <div className="flex items-center justify-between">
                    <div className="flex items-center">
                        <input
                            id="remember-me"
                            type="checkbox"
                            className="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded"
                            checked={remember}
                            onChange={(e) => setRemember(e.target.checked)}
                        />
                        <label htmlFor="remember-me" className="ml-2 block text-sm text-gray-900">
                            Мені есте сақта
                        </label>
                    </div>
                    <div>
                        <Link href="/forgot-password" title="sm" className="text-sm text-gray-600 hover:text-indigo-500">
                            Құпия сөзді ұмыттыңыз ба?
                        </Link>
                    </div>
                </div>

                <div>
                    <button
                        type="submit"
                        disabled={loading}
                        className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:bg-indigo-400"
                    >
                        <span className="absolute left-0 inset-y-0 flex items-center pl-3">
                            <LockClosedIcon className="h-5 w-5 text-indigo-500 group-hover:text-indigo-400" aria-hidden="true" />
                        </span>
                        {loading ? (
                            <svg className="animate-spin h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                            </svg>
                        ) : (
                            'Кіру'
                        )}
                    </button>
                </div>

                <div className="relative my-6">
                    <div className="absolute inset-0 flex items-center">
                        <div className="w-full border-t border-gray-300"></div>
                    </div>
                    <div className="relative flex justify-center text-sm">
                        <span className="px-2 bg-white text-gray-500">Немесе</span>
                    </div>
                </div>

                <div className="flex justify-center">
                    <GoogleLogin
                        onSuccess={handleGoogleSuccess}
                        onError={() => {
                            setErrorMsg('Google арқылы кіру сәтсіз аяқталды');
                        }}
                    />
                </div>
            </form>
        </>
    );
}
