// resources/js/components/Gallery.vue
<template>
    <div v-if="images && images.length > 0" class="my-8">
        <h2 class="text-2xl font-semibold text-center mb-6 text-gray-800 font-baltica">{{ title }}</h2>

        <!-- Grid Layout -->
        <div class="grid grid-cols-2 md:grid-cols-3 gap-4 px-4 sm:px-0">
            <div v-for="(image, index) in images" :key="index"
                class="relative group cursor-pointer overflow-hidden rounded-lg shadow-md aspect-square"
                @click="openLightbox(index)">
                <img :src="getImageUrl(image)"
                    class="w-full h-full object-cover transition-transform duration-300 group-hover:scale-110"
                    alt="Gallery Image" />
                <div
                    class="absolute inset-0 bg-black/40 transition-opacity duration-300 flex items-center justify-center opacity-0 group-hover:opacity-100">
                    <div
                        class="bg-white/20 backdrop-blur-md rounded-full p-4 transform scale-50 group-hover:scale-100 transition-transform duration-300 border border-white/30 text-white">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0zM10 7v3m0 0v3m0-3h3m-3 0H7" />
                        </svg>
                    </div>
                </div>
            </div>
        </div>

        <!-- Lightbox Modal -->
        <Transition name="fade">
            <div v-if="isOpen"
                class="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-95 backdrop-blur-sm"
                @click.self="closeLightbox">
                <!-- Close Button -->
                <button @click="closeLightbox"
                    class="absolute top-4 right-4 text-white hover:text-gray-300 focus:outline-none z-50 p-2">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>

                <!-- Navigation Buttons -->
                <button v-if="images.length > 1" @click.stop="prevImage"
                    class="absolute left-4 text-white hover:text-gray-300 focus:outline-none z-50 p-2 bg-black bg-opacity-50 rounded-full hover:bg-opacity-75 transition-colors">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
                    </svg>
                </button>

                <button v-if="images.length > 1" @click.stop="nextImage"
                    class="absolute right-4 text-white hover:text-gray-300 focus:outline-none z-50 p-2 bg-black bg-opacity-50 rounded-full hover:bg-opacity-75 transition-colors">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                    </svg>
                </button>

                <!-- Main Image -->
                <div class="relative max-w-full max-h-screen p-4 flex items-center justify-center">
                    <Transition name="slide" mode="out-in">
                        <img :key="currentIndex" :src="getImageUrl(images[currentIndex])"
                            class="max-h-[90vh] max-w-[90vw] object-contain shadow-2xl rounded-sm select-none"
                            alt="Gallery Image" @click.stop />
                    </Transition>
                </div>

                <!-- Counter -->
                <div
                    class="absolute bottom-4 left-1/2 transform -translate-x-1/2 text-white text-sm font-medium bg-black bg-opacity-50 px-3 py-1 rounded-full">
                    {{ currentIndex + 1 }} / {{ images.length }}
                </div>
            </div>
        </Transition>
    </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted, watch } from 'vue';

const props = defineProps({
    images: {
        type: Array,
        required: true,
        default: () => []
    },
    title: {
        type: String,
        default: 'Фотогалерея'
    }
});

const isOpen = ref(false);
const currentIndex = ref(0);

const getImageUrl = (image) => {
    if (typeof image === 'string') {
        return image;
    }
    return image.path ? `/storage/${image.path}` : image.url;
};

const openLightbox = (index) => {
    currentIndex.value = index;
    isOpen.value = true;
    document.body.style.overflow = 'hidden'; // Prevent scrolling
};

const closeLightbox = () => {
    isOpen.value = false;
    document.body.style.overflow = ''; // Restore scrolling
};

const nextImage = () => {
    currentIndex.value = (currentIndex.value + 1) % props.images.length;
};

const prevImage = () => {
    currentIndex.value = (currentIndex.value - 1 + props.images.length) % props.images.length;
};

const handleKeydown = (e) => {
    if (!isOpen.value) return;

    if (e.key === 'Escape') {
        closeLightbox();
    } else if (e.key === 'ArrowRight') {
        nextImage();
    } else if (e.key === 'ArrowLeft') {
        prevImage();
    }
};

onMounted(() => {
    window.addEventListener('keydown', handleKeydown);
});

onUnmounted(() => {
    window.removeEventListener('keydown', handleKeydown);
    document.body.style.overflow = ''; // Ensure scrolling is restored
});
</script>

<style scoped>
.fade-enter-active,
.fade-leave-active {
    transition: opacity 0.3s ease;
}

.fade-enter-from,
.fade-leave-to {
    opacity: 0;
}

.slide-enter-active,
.slide-leave-active {
    transition: all 0.3s ease;
}

.slide-enter-from {
    opacity: 0;
    transform: scale(0.95);
}

.slide-leave-to {
    opacity: 0;
    transform: scale(0.95);
}
</style>

// frontend/src/components/Gallery.tsx
'use client';

import React, { useState, useEffect, useCallback } from 'react';
import Image from 'next/image';
import { XMarkIcon, ChevronLeftIcon, ChevronRightIcon, MagnifyingGlassPlusIcon } from '@heroicons/react/24/outline';

interface GalleryProps {
    images: any[];
    title?: string;
}

const Gallery: React.FC<GalleryProps> = ({ images = [], title = 'Фотогалерея' }) => {
    const [isOpen, setIsOpen] = useState(false);
    const [currentIndex, setCurrentIndex] = useState(0);

    const getImageUrl = (image: any) => {
        if (typeof image === 'string') return image;
        return image.path ? `/storage/${image.path}` : image.url;
    };

    const openLightbox = (index: number) => {
        setCurrentIndex(index);
        setIsOpen(true);
        document.body.style.overflow = 'hidden';
    };

    const closeLightbox = useCallback(() => {
        setIsOpen(false);
        document.body.style.overflow = '';
    }, []);

    const nextImage = useCallback(() => {
        setCurrentIndex((prev) => (prev + 1) % images.length);
    }, [images.length]);

    const prevImage = useCallback(() => {
        setCurrentIndex((prev) => (prev - 1 + images.length) % images.length);
    }, [images.length]);

    useEffect(() => {
        const handleKeydown = (e: KeyboardEvent) => {
            if (!isOpen) return;
            if (e.key === 'Escape') closeLightbox();
            if (e.key === 'ArrowRight') nextImage();
            if (e.key === 'ArrowLeft') prevImage();
        };

        window.addEventListener('keydown', handleKeydown);
        return () => {
            window.removeEventListener('keydown', handleKeydown);
            document.body.style.overflow = '';
        };
    }, [isOpen, closeLightbox, nextImage, prevImage]);

    if (!images || images.length === 0) return null;

    return (
        <div className="my-8">
            <h2 className="text-2xl font-semibold text-center mb-6 text-gray-800 font-baltica">{title}</h2>

            {/* Grid Layout */}
            <div className="grid grid-cols-2 md:grid-cols-3 gap-4 px-4 sm:px-0">
                {images.map((image, index) => (
                    <div
                        key={index}
                        className="relative group cursor-pointer overflow-hidden rounded-lg shadow-md aspect-square"
                        onClick={() => openLightbox(index)}
                    >
                        <Image
                            src={image.path}
                            className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-110"
                            alt="Gallery Image"
                            width={300}
                            height={300}
                            unoptimized={image.path?.includes('localhost:8000')}
                        />
                        <div className="absolute inset-0 bg-black/40 transition-opacity duration-300 flex items-center justify-center opacity-0 group-hover:opacity-100">
                            <div className="bg-white/20 backdrop-blur-md rounded-full p-4 transform scale-50 group-hover:scale-100 transition-transform duration-300 border border-white/30 text-white">
                                <MagnifyingGlassPlusIcon className="h-8 w-8" />
                            </div>
                        </div>
                    </div>
                ))}
            </div>

            {/* Lightbox Modal */}
            {isOpen && (
                <div
                    className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-95 backdrop-blur-sm transition-opacity duration-300"
                    onClick={(e) => e.target === e.currentTarget && closeLightbox()}
                >
                    {/* Close Button */}
                    <button
                        onClick={closeLightbox}
                        className="absolute top-4 right-4 text-white hover:text-gray-300 focus:outline-none z-50 p-2"
                    >
                        <XMarkIcon className="h-8 w-8" />
                    </button>

                    {/* Navigation Buttons */}
                    {images.length > 1 && (
                        <>
                            <button
                                onClick={(e) => { e.stopPropagation(); prevImage(); }}
                                className="absolute left-4 text-white hover:text-gray-300 focus:outline-none z-50 p-2 bg-black bg-opacity-50 rounded-full hover:bg-opacity-75 transition-colors"
                            >
                                <ChevronLeftIcon className="h-8 w-8" />
                            </button>

                            <button
                                onClick={(e) => { e.stopPropagation(); nextImage(); }}
                                className="absolute right-4 text-white hover:text-gray-300 focus:outline-none z-50 p-2 bg-black bg-opacity-50 rounded-full hover:bg-opacity-75 transition-colors"
                            >
                                <ChevronRightIcon className="h-8 w-8" />
                            </button>
                        </>
                    )}

                    {/* Main Image */}
                    <div className="relative max-w-full max-h-screen p-4 flex items-center justify-center">
                        <Image
                            src={images[currentIndex].path}
                            className="max-h-[90vh] max-w-[90vw] object-contain shadow-2xl rounded-sm select-none animate-in fade-in zoom-in duration-300"
                            alt="Gallery Image Full"
                            width={1200}
                            height={1200}
                        />
                    </div>

                    {/* Counter */}
                    <div className="absolute bottom-4 left-1/2 transform -translate-x-1/2 text-white text-sm font-medium bg-black bg-opacity-50 px-3 py-1 rounded-full">
                        {currentIndex + 1} / {images.length}
                    </div>
                </div>
            )}
        </div>
    );
};

export default Gallery;
