// resources/js/components/Modal.vue
<template>
  <transition name="fade">
    <div v-if="modal" class="relative z-0">
      <div @click="$emit('closeModal')" class="fixed inset-0 opacity-70 bg-gray-500 z-40"></div>
      <div class="fixed inset-0 z-50 w-screen overflow-y-auto">
        <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
          <div
            class="relative transform m-auto overflow-hidden rounded-lg bg-white text-left shadow-xl transition-all sm:my-8 w-full sm:max-w-lg">
            <div class="bg-white">
              <div class="flex justify-end">
                <XMarkIcon @click="$emit('closeModal')" class="w-6 h-6 cursor-pointer text-red-500 mt-2 mr-2" />
              </div>
              <h3 v-if="title"
                class="text-lg text-center font-semibold leading-6 text-gray-900 pb-4 border-b border-gray-300"
                id="modal-title">{{ title }}</h3>
              <div>
                <slot></slot>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </transition>
</template>

<script setup>
import { XMarkIcon } from '@heroicons/vue/24/outline';
const props = defineProps({
  modal: Boolean,
  title: String
});


</script>

<style scoped>
/*.enter {*/
/*    opacity: 0;*/
/*    transform: translateY(0px);*/
/*}*/

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 400ms ease-in-out;
}
</style>

// frontend/src/components/Modal.tsx
'use client';

import React, { Fragment } from 'react';
import { Dialog, Transition } from '@headlessui/react';
import { XMarkIcon } from '@heroicons/react/24/outline';

interface ModalProps {
    modal: boolean;
    title?: string;
    onClose: () => void;
    children: React.ReactNode;
}

const Modal: React.FC<ModalProps> = ({ modal, title, onClose, children }) => {
    return (
        <Transition.Root show={modal} as={Fragment}>
            <Dialog as="div" className="relative z-50" onClose={onClose}>
                <Transition.Child
                    as={Fragment}
                    enter="ease-out duration-300"
                    enterFrom="opacity-0"
                    enterTo="opacity-100"
                    leave="ease-in duration-200"
                    leaveFrom="opacity-100"
                    leaveTo="opacity-0"
                >
                    <div className="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" />
                </Transition.Child>

                <div className="fixed inset-0 z-10 w-screen overflow-y-auto">
                    <div className="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
                        <Transition.Child
                            as={Fragment}
                            enter="ease-out duration-300"
                            enterFrom="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                            enterTo="opacity-100 translate-y-0 sm:scale-100"
                            leave="ease-in duration-200"
                            leaveFrom="opacity-100 translate-y-0 sm:scale-100"
                            leaveTo="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                        >
                            <Dialog.Panel className="relative transform overflow-hidden rounded-lg bg-white text-left shadow-xl transition-all sm:my-8 w-full sm:max-w-lg">
                                <div className="bg-white">
                                    <div className="flex justify-end p-2">
                                        <button onClick={onClose} className="text-red-500 hover:text-red-700">
                                            <XMarkIcon className="w-6 h-6" />
                                        </button>
                                    </div>
                                    {title && (
                                        <Dialog.Title
                                            as="h3"
                                            className="text-lg text-center font-semibold leading-6 text-gray-900 pb-4 border-b border-gray-300"
                                        >
                                            {title}
                                        </Dialog.Title>
                                    )}
                                    <div className="p-4">{children}</div>
                                </div>
                            </Dialog.Panel>
                        </Transition.Child>
                    </div>
                </div>
            </Dialog>
        </Transition.Root>
    );
};

export default Modal;
