// frontend/src/components/Stepper.tsx
'use client';

import React from 'react';
import { CheckIcon } from '@heroicons/react/24/solid';

export interface StepTab {
    title_kk: string;
    title_ru: string;
    isValid: boolean;
}

interface StepperProps {
    step: number;
    tabs?: StepTab[];
    onNext?: () => void;
    onBack?: () => void;
    onComplete?: () => void;
    nextText?: string;
    backText?: string;
    doneText?: string;
    loading?: boolean;
    children: React.ReactNode;
}

const defaultTabs: StepTab[] = [
    {
        title_kk: 'Шаблонды таңдаңыз',
        title_ru: 'Выберите шаблон',
        isValid: true,
    },
    {
        title_kk: 'Шаблонға тексттер енгізу',
        title_ru: 'Вставка текстов в шаблон',
        isValid: true,
    },
    {
        title_kk: 'Форманы толтыру',
        title_ru: 'Заполнение формы',
        isValid: true,
    },
];

const Stepper: React.FC<StepperProps> = ({
    step,
    tabs = defaultTabs,
    onNext,
    onBack,
    onComplete,
    nextText = 'Келесі қадам',
    backText = 'Артқа',
    doneText = 'Соңы',
    loading = false,
    children,
}) => {
    const progress = ((step - 1) / (tabs.length - 1)) * 100;

    return (
        <div className="w-full mx-auto px-4 py-8">
            {/* Stepper Header */}
            <div className="relative mb-20">
                <div className="absolute top-1/2 left-0 w-full h-0.5 bg-gray-200 -translate-y-1/2 z-0" />
                <div
                    className="absolute top-1/2 left-0 h-0.5 bg-theme-secondary -translate-y-1/2 z-0 transition-all duration-500 ease-in-out"
                    style={{ width: `${progress}%` }}
                />

                <div className="relative z-10 flex justify-between">
                    {tabs.map((tab, index) => {
                        const stepNumber = index + 1;
                        const isCurrent = step === stepNumber;
                        const isCompleted = step > stepNumber;

                        return (
                            <div key={index} className="flex flex-col items-center group">
                                <div
                                    className={`w-12 h-12 sm:w-16 sm:h-16 rounded-full flex items-center justify-center border-2 transition-all duration-500 ${isCurrent
                                        ? 'bg-theme-secondary border-theme-secondary text-white'
                                        : isCompleted
                                            ? 'bg-white border-theme-secondary text-theme-secondary'
                                            : 'bg-white border-gray-200 text-gray-400'
                                        }`}
                                >
                                    {isCompleted ? (
                                        <CheckIcon className="w-6 h-6 sm:w-8 sm:h-8" />
                                    ) : (
                                        <span className="text-xl sm:text-2xl font-bold">{stepNumber}</span>
                                    )}
                                </div>
                                <span
                                    className={`absolute -bottom-10 text-center text-xs sm:text-sm font-medium w-32 transition-colors duration-500 ${isCurrent ? 'text-gray-900' : isCompleted ? 'text-theme-secondary' : 'text-gray-400'
                                        }`}
                                >
                                    {tab.title_kk}
                                </span>
                            </div>
                        );
                    })}
                </div>
            </div>

            {/* Controls */}
            <div className="flex justify-between items-center mb-4">
                {step > 1 && (
                    <button
                        onClick={onBack}
                        className="px-6 py-3 text-sm bg-white border-2 border-gray-200 text-gray-600 font-bold rounded-full hover:bg-gray-50 transition-all cursor-pointer"
                    >
                        {backText}
                    </button>
                )}
                <div className="ml-auto">
                    {step < tabs.length ? (
                        <button
                            onClick={onNext}
                            disabled={!tabs[step - 1].isValid || loading}
                            className="px-6 py-3 bg-theme-secondary text-sm text-white font-bold rounded-full hover:shadow-lg disabled:opacity-50 flex items-center transition-all cursor-pointer"
                        >
                            {loading && (
                                <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                </svg>
                            )}
                            {nextText}
                        </button>
                    ) : (
                        <button
                            onClick={onComplete}
                            disabled={!tabs[step - 1].isValid || loading}
                            className="px-6 py-3 bg-green-600 text-sm text-white font-bold rounded-full hover:shadow-lg disabled:opacity-50 flex items-center transition-all cursor-pointer"
                        >
                            {loading && (
                                <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                </svg>
                            )}
                            {doneText}
                        </button>
                    )}
                </div>
            </div>

            {/* Content */}
            <div className="bg-white rounded-2xl shadow-xl p-6 border border-gray-200 sm:p-10 mb-8 min-h-[400px]">
                {children}
            </div>


        </div>
    );
};

export default Stepper;

// resources/js/components/Stepper.vue
<template>
  <div class="wrapper-steppy" :style="cssVars">
    <div class="steppy">
      <div class="steppy-progress">
        <div
            class="steppy-progress-bar"
            :style="'width:' + steppyProgress"
        ></div>
      </div>

      <div
          class="steppy-item"
          :class="{
          current: props.step === index + 1,
          success: props.step > index + 1,
        }"
          v-for="(item, index) in props.tabs"
          :key="index"
      >
        <div class="steppy-item-counter" :style="circleStyles">
          <img
              v-if="item.iconSuccess"
              class="icon-success"
              :src="item.iconSuccess"
              alt="Check Mark"
          />
          <CheckMark
              v-else
              class="icon-success"
              :color="primaryColor1"
              alt="Check Mark"
          />
          <span class="number">{{ index + 1 }}</span>
        </div>
        <span class="steppy-item-title max-w-[120px] text-xs sm:text-sm">{{ item['title_'+$i18n.locale] }}</span>
      </div>
    </div>

    <div class="controls">
      <button
          class="btn"
          type="button"
          @click="decrementStep"
          v-if="props.step !== 1"
      >
        {{ props.backText }}
      </button>
      <button
          class="btn btn--default-2"
          type="button"
          @click="incrementStep"
          v-if="props.step !== props.tabs.length"
          :disabled="!props.tabs[props.step - 1].isValid"
      >
        {{ props.nextText }}
      </button>
      <button
          class="btn btn--default-2"
          type="button"
          @click="complete"
          v-else
          :disabled="!props.tabs[props.step - 1].isValid || loading"
      >
        <span v-if="loading" class="loader"></span>
        <span v-else>{{ props.doneText }}</span>
      </button>
    </div>

    <div class="steppy-content" v-for="index in props.tabs.length" :key="index">
      <div class="steppy-pane" v-if="props.step === index">
        <slot :name="index"></slot>
      </div>
    </div>


  </div>
</template>

<script setup>
import { computed, reactive } from "vue";
import CheckMark from "./CheckMark.vue";

const emit = defineEmits(["update:step","incrementStep","decrementStep"]);

const props = defineProps({
  step: {
    type: Number,
    default: 1,
  },
  tabs: {
    type: Array,
    default: reactive([
      {
        title_kk: 'Шаблонды таңдаңыз',
        title_ru: 'Выберите шаблон',
        iconSuccess: null,
        isValid: true,
      },
      {
        title_kk: "Шаблонға тексттер енгізу",
        title_ru: "Вставка текстов в шаблон",
        iconSuccess: null,
        isValid: true,
      },
      {
        title_kk: "Форманы толтыру",
        title_ru: "Заполнение формы",
        iconSuccess: null,
        isValid: true,
      },
    ]),
  },
  finalize: {
    type: Function,
    default: function () {
      return {};
    },
  },
  backText: {
    type: String,
    default: "Артқа",
  },
  nextText: {
    type: String,
    default: "Келесі қадам",
  },
  doneText: {
    type: String,
    default: "Соңы",
  },
  loading: {
    type: Boolean,
    default: false,
  },
  permission: {
    type: Boolean,
    default: true,
  },
  primaryColor1: {
    type: String,
    default: "#CB997E",
  },
  primaryColor2: {
    type: String,
    default: "#fff",
  },
  circleSize: {
    type: Number,
    default: 68,
  },
});

const cssVars = computed(() => {
  return {
    "--primaryColor1": props.primaryColor1,
    "--primaryColor2": props.primaryColor2,
    "--circleSize": `${props.circleSize}px`,
  };
});

const incrementStep = () => {

  // const step = props.step + 1;
  //  emit("update:step", step);

  emit("incrementStep");

};

const complete = () => {
    emit("complete")
}

const decrementStep = () => {
 // const step = props.step - 1;
 // emit("update:step", step);
  emit("decrementStep");
};

const steppyProgress = computed(() => {
  return (100 / (props.tabs.length - 1)) * (props.step - 1) + "%";
});

const circleStyles = computed(() => {
  return {
    height: `${props.circleSize}px`,
    width: `${props.circleSize}px`,
  };
});
</script>

<style scoped lang="scss">
$primary-1: var(--primaryColor1);
$primary-2: var(--primaryColor2);
$transition: all 500ms ease;


.tx-default-2 {
  color: $primary-1;
  font-weight: 600;
}

.wrapper-steppy {
  padding: 20px;
}

.steppy {
  display: flex;
  align-items: center;
  justify-content: space-between;
  width: auto;
  position: relative;
  z-index: 0;
  margin-bottom: 5px;

  &-progress {
    position: absolute;
    background-color: #c5c5c5;
    height: 2px;
    z-index: -1;
    left: 0;
    right: 0;
    margin: 0 auto;

    &-bar {
      position: absolute;
      left: 0;
      height: 100%;
      width: 0;
      background-color: $primary-1;
      transition: $transition;
    }
  }
}

.steppy-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  color: #c5c5c5;
  transition: $transition;

  &-counter {
    height: 68px;
    width: 68px;
    display: grid;
    place-items: center;
    background-color: $primary-2;
    border-radius: 100%;
    border: 2px solid #c5c5c5;
    position: relative;

    .icon-success {
      position: absolute;
      opacity: 0;
      transform: scale(0);
      width: 24px;
      transition: $transition;
    }

    .number {
      font-size: 22px;
      transition: $transition;
    }
  }

  &-title {
    position: absolute;
    text-align: center;
    font-size: 12px;
    bottom: -43px;
  }
}

.steppy-item.success {
  .steppy-item-counter {
    border-color: $primary-1;
    font-weight: 600;
    height: var(--circleSize);
    width: var(--circleSize);

    .icon-success {
      opacity: 1;
      transform: scale(1);
      width: calc(var(--circleSize) * 0.35);
    }

    .number {
      opacity: 0;
      transform: scale(0);
      font-size: calc(var(--circleSize) * 0.32);
    }
  }

  .steppy-item-title {
    color: $primary-1;
  }
}

.steppy-item.current {
  .steppy-item-counter {
    border-color: $primary-1;
    background-color: $primary-1;
    color: #fff;
    font-weight: 600;
  }

  .steppy-item-title {
    color: #818181;
  }
}

.steppy-pane {
  color: #333;
  text-align: center;
  background-color: #fff;
  border-radius: 15px;
  padding: 25px 25px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
  margin: 60px 0 20px 0;
}

@media (max-width: 500px) { 
  .steppy-pane {
    padding: 0;
   }
 }

.controls {
  margin-top: 60px;
  display: flex;
}

.btn {
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 6px 16px;
  text-align: center;
  vertical-align: middle;
  cursor: pointer;
  line-height: 1.5;
  transition: all 150ms;
  border-radius: 4px;
  width: fit-content;
  font-size: 0.75rem;
  color: #333;
  background-color: #f0f0f0;
  border: 1px solid #f0f0f0;

  &:disabled {
    opacity: 0.5;
    pointer-events: none;
  }

  &--default-2 {
    background-color: $primary-1;
    border-color: $primary-1;
    color: #fff;
    margin-left: auto;
  }
}

.loader {
  width: 20px;
  height: 20px;
  border: 2px solid #fff;
  border-bottom-color: transparent;
  border-radius: 50%;
  display: inline-block;
  box-sizing: border-box;
  animation: rotation 1s linear infinite;
}

@keyframes rotation {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
</style>
