// frontend/src/app/[locale]/app/select-template/page.tsx
'use client';

import React, { useState, useEffect, Suspense } from 'react';
import { useRouter } from '@/i18n/routing';
import { useSearchParams } from 'next/navigation';
import { useAppStore } from '@/store/useAppStore';
import Stepper from '@/components/Stepper';
import Spinner from '@/components/Spinner';
import Pagination from '@/components/Pagination';
import Modal from '@/components/Modal';
import { PlayIcon } from '@heroicons/react/24/outline';
import { useTranslations, useLocale } from 'next-intl';

const SelectTemplateContent = () => {
    const router = useRouter();
    const searchParams = useSearchParams();
    const t = useTranslations('SelectTemplate');
    const tCommon = useTranslations('Common');
    const locale = useLocale();
    const { templateCategories, getTemplateCategories } = useAppStore();

    const [selectedCategory, setSelectedCategory] = useState<number>(1);
    const [currentPage, setCurrentPage] = useState<number>(1);
    const [modal, setModal] = useState(false);
    const [modalTitle, setModalTitle] = useState('');
    const [modalVideoUrl, setModalVideoUrl] = useState('');

    const itemsPerPage = 6;

    useEffect(() => {
        getTemplateCategories();
    }, [getTemplateCategories]);

    useEffect(() => {
        const categoryFromUrl = searchParams.get('category');
        const pageFromUrl = searchParams.get('page');

        if (categoryFromUrl) {
            setSelectedCategory(parseInt(categoryFromUrl, 10));
        }
        if (pageFromUrl) {
            setCurrentPage(parseInt(pageFromUrl, 10));
        }
    }, [searchParams]);

    const categories = templateCategories.data || [];
    const loading = templateCategories.loading;

    const activeCategory = categories.find((cat: any) => cat.id === selectedCategory);
    const filteredTemplates = activeCategory?.templates || [];

    const totalPages = Math.ceil(filteredTemplates.length / itemsPerPage);
    const start = (currentPage - 1) * itemsPerPage;
    const end = start + itemsPerPage;
    const paginatedTemplates = filteredTemplates.slice(start, end);

    const openModal = (title: string, videoUrl: string) => {
        setModalVideoUrl(videoUrl);
        setModalTitle(title);
        setModal(true);
    };

    const closeModal = () => setModal(false);

    const selectCategory = (categoryId: number) => {
        setSelectedCategory(categoryId);
        setCurrentPage(1);
        const params = new URLSearchParams(searchParams.toString());
        params.set('category', categoryId.toString());
        params.set('page', '1');
        router.replace(`/app/select-template?${params.toString()}`);
    };

    const handlePageChange = (page: number) => {
        setCurrentPage(page);
        const params = new URLSearchParams(searchParams.toString());
        params.set('page', page.toString());
        router.replace(`/app/select-template?${params.toString()}`);
    };

    const selectTemplate = (templateId: number) => {
        router.push(`/app/invitation-create/${templateId}`);
    };

    return (
        <div className="container mx-auto">
            <Stepper step={1}>
                <div id="features" className="container mx-auto px-0 sm:px-5">
                    <section className="py-8 sm:py-16">
                        <div className="w-full md:w-4/5 lg:w-3/5 mx-auto">
                            <h2 className="text-2xl md:text-3xl font-bold text-center text-gray-900">
                                {t('title')}
                            </h2>
                            <p className="text-gray-500 text-center my-7 text-lg">
                                {t('subtitle')}
                            </p>

                            <div className="flex justify-center space-x-4">
                                <button
                                    onClick={() => openModal(t('example_button'), '/video/Instructions.mp4')}
                                    className="flex items-center bg-theme-primary cursor-pointer px-6 py-2 text-white rounded-lg hover:bg-white border-2 border-transparent hover:border-theme-primary hover:text-theme-primary transition-all font-bold shadow-md"
                                >
                                    <PlayIcon className="w-6 h-6 mr-2" />
                                    <span>{t('example_button')}</span>
                                </button>
                                <button
                                    onClick={() => openModal(t('personal_invite_button'), '/video/preview.mp4')}
                                    className="flex items-center bg-theme-primary cursor-pointer px-6 py-2 text-white rounded-lg hover:bg-white border-2 border-transparent hover:border-theme-primary hover:text-theme-primary transition-all font-bold shadow-md"
                                >
                                    <PlayIcon className="w-6 h-6 mr-2" />
                                    <span>{t('personal_invite_button')}</span>
                                </button>
                            </div>
                        </div>
                        <div className="mt-12 overflow-x-auto">
                            <ul className="flex flex-nowrap md:flex-wrap justify-start md:justify-center border-b border-gray-100 min-w-max">
                                {categories.map((category: any) => (
                                    <li
                                        key={category.id}
                                        className={`cursor-pointer transition duration-300 px-8 py-4 font-bold text-sm uppercase tracking-wider ${selectedCategory === category.id
                                            ? 'text-theme-secondary border-b-4 border-theme-secondary'
                                            : 'text-gray-400 hover:text-gray-600 border-b-2 border-gray-200'
                                            }`}
                                        onClick={() => selectCategory(category.id)}
                                    >
                                        {locale === 'kk' ? category.title_kk : category.title_ru}
                                    </li>
                                ))}
                            </ul>
                        </div>

                        <div className="mt-12">
                            {loading ? (
                                <Spinner />
                            ) : (
                                <>
                                    <div className="grid gap-8 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 items-center">
                                        {paginatedTemplates.map((template: any) => (
                                            <div
                                                key={template.id}
                                                onClick={() => selectTemplate(template.id)}
                                                className="relative cursor-pointer group rounded-2xl overflow-hidden hover:shadow-2xl transition duration-500 bg-white"
                                            >
                                                <div className="absolute right-4 top-4 z-10 bg-indigo-600 text-white px-4 py-1 rounded-full text-xs font-bold opacity-0 group-hover:opacity-100 transform translate-y-2 group-hover:translate-y-0 transition duration-500">
                                                    {tCommon('select')}
                                                </div>
                                                <div className="absolute left-4 bottom-4 z-10 font-bold text-green-600 bg-white/90 px-3 py-1 rounded-lg shadow-sm">
                                                    {template.price} тг
                                                </div>
                                                <img
                                                    src={template.preview_img}
                                                    alt={template.title}
                                                    className="w-full h-auto object-cover transform transition duration-700"
                                                    loading="lazy"
                                                />
                                            </div>
                                        ))}
                                    </div>

                                    <Pagination
                                        currentPage={currentPage}
                                        totalPages={totalPages}
                                        onPageChanged={handlePageChange}
                                        className="mt-16"
                                    />
                                </>
                            )}
                        </div>
                    </section>
                </div>
            </Stepper>


            <Modal modal={modal} title={modalTitle} onClose={closeModal}>
                <div className="w-full aspect-[9/16] max-w-[320px] mx-auto overflow-hidden rounded-2xl shadow-2xl">
                    <iframe
                        src={modalVideoUrl}
                        className="w-full h-full"
                        allowFullScreen
                        allow="autoplay"
                    ></iframe>
                </div>
            </Modal>
        </div>
    );
};

export default function SelectTemplatePage() {
    return (
        <Suspense fallback={<Spinner />}>
            <SelectTemplateContent />
        </Suspense>
    );
}

// resources/js/views/app/SelectTemplate.vue
<template>
  <div class="container mx-auto">
    <Stepper :step="1" :nextText="$t('nextStep')">
      <template #1>
        <div id="features" class="container mx-auto px-5">
          <section class="py-16">
            <div class="w-full md:w-3/5 mx-auto">
              <h2 class="text-2xl md:text-3xl font-semibold text-center">{{ $t('choose a template for your upcoming evet') }}!</h2>
              <p class="text-theme-grayish-blue text-center my-7 font-theme-content text-md">
                {{ $t('we have prepared templates for various events. Making an online invitation is now easy') }}!
              </p>
              <div class="flex justify-center">
                <button @click="openModal('Үлгі','/video/Instructions.mp4')"
                     class="flex bg-theme-primary cursor-pointer px-6 py-2 text-white rounded focus:ring-4 focus:outline-none focus:ring-primary transition-all font-semibold mr-2">
                     <PlayIcon class="w-6 h-6 mr-1"/>
                     <span>Үлгі</span></button>
              <button @click="openModal('Жеке шақыру','/video/preview.mp4')"
                     class="flex bg-theme-primary cursor-pointer px-6 py-2 text-white rounded focus:ring-4 focus:outline-none focus:ring-primary transition-all font-semibold">
                     <PlayIcon class="w-6 h-6 mr-1"/>
                     <span>Жеке шақыру</span></button>
              </div>
              
            </div>

            <div class="mt-10">
              <ul class="flex flex-col items-center md:flex-row justify-center">
                <li v-for="category in categories" 
                    :key="category.id" 
                    :class="{'md:border-b-4 md:border-theme-secondary': selectedCategory === category.id}"
                    class="w-full md:w-56 cursor-pointer hover:text-theme-secondary transition duration-200 border-gray-300 border-b-2 border-t-2 md:border-t-0 flex justify-center">
                  <a @click="selectCategory(category.id)" 
                     href="#" 
                     :class="selectedCategory === category.id ? 'border-theme-secondary' : ''" 
                     class="py-5 md:border-b-0 border-b-4">
                    {{ category[`title_${$i18n.locale}`] }}
                  </a>
                </li>
              </ul>
            </div>

            <div class="mt-16">
              <div v-if="loading" class="relative">
                <Spinner />
              </div>
              <div v-else>
                <div class="grid gap-8 lg:grid-cols-3 items-center">
                  <div v-for="template in paginatedTemplates" 
                       :key="template.id" 
                       @click="selectTemplate(template.id)" 
                       class="relative cursor-pointer group hover:border">
                    <div class="absolute right-4 top-4 bg-theme-primary text-white p-1 rounded text-sm opacity-0 group-hover:opacity-100">{{ $t('choice') }}</div>
                    <div class="absolute right-4 bottom-4 font-semibold text-green-500 rounded text-lg">{{ template.price }} тг</div>
                    <img 
                      v-lazy-load
                      :data-src="template.preview_img" 
                      :alt="template.title"
                      class="template-image"
                      @load="onImageLoad"
                    >
                    <div v-if="!template.loaded" class="absolute inset-0 bg-gray-200 animate-pulse"></div>
                  </div>
                </div>
                
                <!-- Pagination -->
                <Pagination
              :currentPage="currentPage"
              :totalPages="totalPages"
              @page-changed="handlePageChange"
              class="mt-8"
            />
              </div>
            </div>
          </section>
        </div>
      </template>
    </Stepper>
  </div>
    <Modal :modal="modal" :title="modal_title" @close-modal="closeModal">
  <iframe
       :src="modal_video_url"
       class="w-full max-w-sm mx-auto aspect-[9/16]"
       controls="1"
      allowfullscreen
      allowtransparency
      allow="autoplay"
    ></iframe>
        
    </Modal>
</template>

<script setup>
import { ref, computed, onMounted, watch, defineAsyncComponent } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import { useStore } from 'vuex';
import Stepper from "../../components/Stepper.vue";
import Spinner from '../../components/core/Spinner.vue';
import Pagination from "../../components/core/Pagination.vue";
import Modal from "../../components/Modal.vue";
import { PlayIcon } from '@heroicons/vue/24/outline'

const store = useStore();
const router = useRouter();
const route = useRoute();

const selectedCategory = ref(1);
const currentPage = ref(1);
const itemsPerPage = 6;

const loading = computed(() => store.state.app.templateCategories.loading);
const categories = computed(() => store.state.app.templateCategories.data);

// const filteredTemplates = computed(() => categories.value?.find((item) => item.id === selectedCategory.value)?.templates || []);
const filteredTemplates = computed(() => {
  const templates = categories.value?.find((item) => item.id === selectedCategory.value)?.templates || [];
  return templates.map(template => ({
    ...template,
    loaded: ref(false)
  }));
});

const totalPages = computed(() => Math.ceil(filteredTemplates.value.length / itemsPerPage));

const paginatedTemplates = computed(() => {
  const start = (currentPage.value - 1) * itemsPerPage;
  const end = start + itemsPerPage;
  return filteredTemplates.value.slice(start, end);
});

const vLazyLoad = {
  mounted(el) {
    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          el.src = el.dataset.src;
          observer.unobserve(el);
        }
      });
    }, { rootMargin: '50px' });
    observer.observe(el);
  }
};

let modal =  ref(false);
let modal_title = ref('');
let modal_video_url = ref('');

function openModal(title,video_url){
    modal_video_url.value = video_url;
    modal_title.value = title;
    modal.value = true;
}
function closeModal(){
    modal.value = false;
}

function onImageLoad(event) {
  const template = paginatedTemplates.value.find(t => t.preview_img === event.target.src);
  if (template) {
    template.loaded = true;
  }
}

function selectCategory(categoryId) {
  selectedCategory.value = categoryId;
  currentPage.value = 1;
  router.replace({
    query: { category: categoryId, page: 1 },
  });
}

function handlePageChange(page) {
  currentPage.value = page;
  router.replace({
    query: { ...route.query, page },
  });
}

function selectTemplate(templateId) {
  router.push({ name: 'Step2', params: { id: templateId } });
}
// watch(selectedCategory, () => {
//   currentPage.value = 1;
// });

watch(
  () => route.query,
  (newQuery) => {
    const categoryFromUrl = newQuery.category ? parseInt(newQuery.category, 10) : 1;
    const pageFromUrl = newQuery.page ? parseInt(newQuery.page, 10) : 1;

    if (categories.value.some((cat) => cat.id === categoryFromUrl)) {
      selectedCategory.value = categoryFromUrl;
    }
    if (pageFromUrl > 0 && pageFromUrl <= totalPages.value) {
      currentPage.value = pageFromUrl;
    }
  }
);

onMounted(() => {
  store.dispatch('app/getTemplateCategories');

  // Чтение параметров из URL
  const categoryFromUrl = route.query.category ? parseInt(route.query.category, 10) : 1;
  const pageFromUrl = route.query.page ? parseInt(route.query.page, 10) : 1;

  // Проверка, существует ли категория
  if (categories.value && categories.value.some((cat) => cat.id === categoryFromUrl)) {
    selectedCategory.value = categoryFromUrl;
  }
  // Проверка, валидна ли страница
  if (pageFromUrl > 0 && pageFromUrl <= totalPages.value) {
    currentPage.value = pageFromUrl;
  }
});
</script>

<style scoped>
/* Add any scoped styles here */
</style>
